from argparse import ArgumentParser
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
import scipy.linalg as spla
from irdl import FabianDataset

from src.plotting import (
    COLUMN_WIDTH_IN,
    GOLDEN_RATIO,
    SELECTED_ORDER_MARKER_STYLE,
    golden_axes,
    plot_color,
)
from src.utils import (
    REDUCED_ORDER,
    dB,
    delay_shifts,
    make_era,
    prepare_impulse_response,
    restore_delays,
)


OUTPUT_DIR = Path("generated/figures")
RESULTS = Path("generated/data/bound-error.npz")
EXPERIMENT_VALUES = RESULTS.with_name("experiment-values.tex")
OUTPUT = OUTPUT_DIR / "bound-error.pdf"
LEGEND = OUTPUT_DIR / "bound-error-legend.pdf"
ORDERS = np.sort(np.append(np.arange(32, 513, 32), REDUCED_ORDER))
Y_LIMITS = (-64, 48)
Y_TICKS = np.arange(-60, 41, 20)
BOUND_STYLES = (
    ("Singular value", ":", 0),
    ("Corrected bound", "-.", 1),
    ("Projection-aware bound", "--", 0),
    ("HRIR error", "-", 0),
)
BOUND_MARKERS = ("o", "s", "^", "D", "v")


def compute():
    """Return singular values, three bounds, and sparse measured errors."""
    impulse_response = prepare_impulse_response(
        FabianDataset.get(hato=0, cache_dir="data")["impulse_response"]
    )
    era, _, n_virtual = make_era(impulse_response)
    n_data, n_outputs, n_inputs = era.reductor.data.shape
    n_response_samples = n_data + 1
    hsv = era.reductor._sv_U_V(None, n_virtual)[0]
    norm = spla.norm(impulse_response.time)

    orders = np.arange(1, len(hsv))
    error_orders = ORDERS[ORDERS < len(hsv)]
    # Pelling & Sarradj (2026), Eq. 27: Kung's corrected H2-error bound.
    corrected_bound = np.sqrt(orders + n_outputs + n_inputs) * hsv[1:] / norm
    tera_bound = era.reductor.error_bounds(None, n_virtual) / norm
    proposed_bound = np.sqrt(orders + n_outputs + n_virtual) * hsv[1:] / norm
    errors = []
    for order in error_orders:
        reduced = era.reduce(order, num_right=n_virtual).impulse_response(n_response_samples)
        errors.append(spla.norm((impulse_response - reduced).time) / norm)

    itd_era, _, itd_n_virtual = make_era(impulse_response, delay_removal="individual")
    itd_n_data, itd_n_outputs, itd_n_inputs = itd_era.reductor.data.shape
    itd_hsv = itd_era.reductor._sv_U_V(None, itd_n_virtual)[0]
    itd_corrected_bound = np.sqrt(orders + itd_n_outputs + itd_n_inputs) * itd_hsv[1:] / norm
    itd_tera_bound = itd_era.reductor.error_bounds(None, itd_n_virtual) / norm
    itd_proposed_bound = np.sqrt(orders + itd_n_outputs + itd_n_virtual) * itd_hsv[1:] / norm
    itd_reference = prepare_impulse_response(impulse_response, delay_removal="individual")
    itd_norm = spla.norm(itd_reference.time)
    itd_errors = []
    itd_aligned_errors = []
    for order in error_orders:
        reduced = itd_era.reduce(order, num_right=itd_n_virtual).impulse_response(itd_n_data + 1)
        itd_aligned_errors.append(spla.norm((itd_reference - reduced).time) / itd_norm)
        reduced = restore_delays(reduced, impulse_response, delay_removal="individual")
        itd_errors.append(spla.norm((impulse_response - reduced).time) / norm)

    return (
        orders,
        error_orders,
        (hsv / norm, corrected_bound, tera_bound, proposed_bound, np.asarray(errors)),
        (
            itd_hsv / norm,
            itd_corrected_bound,
            itd_tera_bound,
            itd_proposed_bound,
            np.asarray(itd_errors),
            np.asarray(itd_aligned_errors),
        ),
    )


def export_experiment_values():
    """Export selected experiment values as LaTeX macros."""
    with np.load(RESULTS) as results:
        index = np.flatnonzero(results["error_orders"] == REDUCED_ORDER)
        if len(index) != 1:
            raise ValueError(f"No unique error result for order {REDUCED_ORDER}")
        raw_error = dB(results["errors"][index[0]])
        itd_error = dB(results["itd_errors"][index[0]])

    impulse_response = FabianDataset.get(hato=0, cache_dir="data")["impulse_response"]
    _, s, _ = make_era(impulse_response)
    _, _, rank_bound = make_era(impulse_response, delay_removal="individual")
    itd_length = s - np.min(delay_shifts(impulse_response, "individual"))
    EXPERIMENT_VALUES.write_text(
        "% Generated by export-experiment-values; do not edit.\n"
        f"\\newcommand{{\\SelectedModelOrder}}{{{REDUCED_ORDER}}}\n"
        f"\\newcommand{{\\OriginalDelayRelativeErrorDB}}{{{raw_error:.1f}}}\n"
        f"\\newcommand{{\\ITDRemovedRelativeErrorDB}}{{{itd_error:.1f}}}\n"
        f"\\newcommand{{\\ITDRemovedLength}}{{{itd_length:g}}}\n"
        f"\\newcommand{{\\ITDRemovedRankBound}}{{{rank_bound:g}}}\n"
    )


def compute_bound_error():
    """Compute and persist the bound/error plot data."""
    orders, error_orders, original_delay, itd_removed = compute()
    RESULTS.parent.mkdir(parents=True, exist_ok=True)
    np.savez(
        RESULTS,
        orders=orders,
        error_orders=error_orders,
        hsv=original_delay[0],
        corrected_bound=original_delay[1],
        tera_bound=original_delay[2],
        proposed_bound=original_delay[3],
        errors=original_delay[4],
        itd_hsv=itd_removed[0],
        itd_corrected_bound=itd_removed[1],
        itd_tera_bound=itd_removed[2],
        itd_proposed_bound=itd_removed[3],
        itd_errors=itd_removed[4],
        itd_aligned_errors=itd_removed[5],
    )


def plot(orders, error_orders, original_delay, itd_removed):
    """Overlay original-delay and ITD-removed ERA bounds on shared axes."""
    figure, axis = plt.subplots(
        figsize=(COLUMN_WIDTH_IN, COLUMN_WIDTH_IN / GOLDEN_RATIO), layout="constrained"
    )
    golden_axes(axis)
    for values, color_family in ((original_delay, "no_removal"), (itd_removed, "itd_removal")):
        hsv, corrected_bound, _, proposed_bound, errors, *extra_errors = values
        for (x, y), (_, linestyle, shade) in zip(
            (
                (np.arange(1, len(hsv) + 1), hsv),
                (orders, corrected_bound),
                (orders, proposed_bound),
                (error_orders, errors),
            ),
            BOUND_STYLES,
        ):
            axis.plot(x, dB(y), color=plot_color(color_family, shade), linestyle=linestyle)
        marker_mask = error_orders != REDUCED_ORDER
        axis.plot(
            error_orders[marker_mask],
            dB(errors[marker_mask]),
            color=plot_color(color_family),
            linestyle="none",
            marker=BOUND_MARKERS[-1],
            markerfacecolor="none",
            zorder=3,
        )
        if extra_errors:
            axis.plot(
                error_orders,
                dB(extra_errors[0]),
                color=plot_color(color_family, 1),
                linestyle="-",
            )
        error_index = np.flatnonzero(error_orders == REDUCED_ORDER)
        if error_index.size:
            axis.plot(
                REDUCED_ORDER,
                dB(errors[error_index[0]]),
                linestyle="none",
                zorder=4,
                **SELECTED_ORDER_MARKER_STYLE,
            )
    axis.set(
        xlabel="Model order",
        ylabel="Relative error in dB",
        xlim=(1, len(original_delay[0])),
        ylim=Y_LIMITS,
        yticks=Y_TICKS,
    )
    axis.minorticks_on()
    axis.grid(which="major", alpha=0.3)
    axis.grid(which="minor", alpha=0.15, linewidth=0.5)
    return figure


def plot_legend():
    """Create the compact external legend for the bound/error figure."""
    figure, axis = plt.subplots(figsize=(COLUMN_WIDTH_IN, 0.9), layout="constrained")
    axis.axis("off")
    handles = [
        Line2D(
            [],
            [],
            color="0.2",
            linestyle=linestyle,
            marker=BOUND_MARKERS[-1] if index == len(BOUND_STYLES) - 1 else None,
            markerfacecolor="none",
            label=label,
        )
        for index, (label, linestyle, _) in enumerate(BOUND_STYLES)
    ]
    handles.extend(
        (
            Line2D([], [], color=plot_color("no_removal"), label="Original-delay error"),
            Line2D([], [], color=plot_color("itd_removal"), label="ITD-restored error"),
            Line2D([], [], color=plot_color("itd_removal", 1), label="ITD-aligned error"),
            Line2D([], [], linestyle="none", label=f"Order {REDUCED_ORDER}", **SELECTED_ORDER_MARKER_STYLE),
        )
    )
    axis.legend(handles=handles, loc="center", ncols=2, frameon=False, fontsize=9)
    return figure


def main():
    parser = ArgumentParser(description="Generate the FABIAN ERA bound/error figure.")
    parser.add_argument("--no-show", action="store_true")
    args = parser.parse_args()

    with np.load(RESULTS) as results:
        original_delay = (
            results["hsv"],
            results["corrected_bound"],
            results["tera_bound"],
            results["proposed_bound"],
            results["errors"],
        )
        itd_removed = (
            results["itd_hsv"],
            results["itd_corrected_bound"],
            results["itd_tera_bound"],
            results["itd_proposed_bound"],
            results["itd_errors"],
            results["itd_aligned_errors"],
        )
        figure = plot(results["orders"], results["error_orders"], original_delay, itd_removed)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    figure.savefig(OUTPUT)
    legend = plot_legend()
    legend.savefig(LEGEND)
    if not args.no_show:
        plt.show()
    plt.close(figure)
    plt.close(legend)


if __name__ == "__main__":
    main()
